# Generated by Django 2.1.2 on 2022-02-27 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('address', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
