# Generated by Django 2.1.2 on 2022-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_blooddonate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donar',
            name='user',
        ),
        migrations.AddField(
            model_name='donar',
            name='Donar_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
