# Generated by Django 2.2 on 2022-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_of_hospital', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Negative', 'AB Negative'), ('AB Positive', 'AB Positive')], default='O Positive', max_length=30)),
                ('units', models.IntegerField()),
                ('reason', models.TextField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
