# Generated by Django 2.1.2 on 2022-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='Patient',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
